For this lab, you are going to be combining the fare data you used in **Lab 1** with some trip data about those same exact taxi rides.

Here is the schema of the trip dataset, found in `trip_data_1_trimmed.csv`:

* `medallion`: The ID of the cab being operated
* `hack_license`: The ID of the person operating the cab
* `vendor_id`: The type of vendor operating the cab, can either be `CMT` or `VTS`, no clue what these two types mean
* `rate_code`: Designates the kind of ride this is, must be `1` through `6`, any other number is incorrect
* `store_and_fwd_flag`: Can be either `Y`,`N`, or Nan
* `pickup_datetime`: The time when the ride started
* `dropoff_datetime`: The time when the ride ended
* `passenger_count`: The number of passengers during the ride
* `trip_time_in_secs`: How long the trip took
* `trip_distance`: Distance of the trip, to the nearest 1/10 mile
* `pickup_longitude`: Longitude of pickup location
* `pickup_latitude`: Latitude of pickup location
* `dropoff_longitude`: Longitude of dropoff location
* `dropoff_latitude`: Latitude of dropoff location

And here is the schema for the fare dataset, as a refresher (you're going to be using it too :)), found in `fare_data_1_trimmed.csv`:

* `medallion`: The ID of the cab being operated
* `hack_license`: The ID of the person operating the cab
* `vendor_id`: The type of vendor operating the cab, can either be `CMT` or `VTS`, no clue what these two types mean
* `pickup_datetime`: The time when the ride started
* `payment_type`: How the trip was paid, `UNK` stands for unknown, I have no idea what `NOC` stands for, but lets assume its some known way to pay
* `fare_amount`: Base fare cost of the trip
* `surcharge`: Additional charges that are not tolls
* `mta_tax`: The mta has to get its cut, right? :)
* `tip_amount`: How generous the rider(s) decided to be
* `tolls_amount`: How much money you had to pay in tolls
* `total_amount`: How much the trip cost, all in

One final piece of information you will need, the approximate latitude/longitude bounds of a bounding box centered around each borough in NYC:

* Queens,40.800760,40.542920,-73.700272,-73.962616
* Manhattan,40.874663,40.701293,-73.910759,-74.018721
* Bronx,40.915255,40.785743,-73.765274,-73.933406
* Brooklyn,40.739877,40.57042,-73.864754,-74.04344
* Staten Island,40.651812,40.477399,-74.034547,-74.259090

So, as was the case with the last lab, you are going to be tasked with answering a whole slew of questions about these data, except the questions here should be significantly more challenging.

Before beginning, please:

1. Remove any rides that did not have an appropriate `rate_code` 
* Convert pickup and dropoff locations from latitude/longitude to (approximate) borough. This will be very challening. I suggest the following approach, although you can try others:
  1. Calculate the exact center of each borough's bounding box and store each in a new variable (you should have one of these per borough, so 5 variables)
  * Find the distance from the given ride's pickup/dropoff location and the center of each borough found in A. 
  * Pick the borough that had the smallest distance from the given location to its bounding box center. (this is messy because it ignores cases where the start/end location isn't in the 5 boroughs, but its the best we can do with the information you're provided)
* Once this is done, join the `trip_data` and `fare_data` datasets together. You will need to join the datasets on more than one column, but you will have to figure out what those columns are!

Once you've gotten the preprocessing out of the way, answer the following questions:

1. What was the most common borough start location?
  * End location?
  * Pair of start/end locations? Excluding manhattan/manhattan?
* Which driver (`hack_license`) carried the most passengers, on average?
* Which driver had the highest tip percentage, on average, for those drivers that made at least 5 trips in the dataset?
* Was there any relationship between (correlation) when a taxi ride ended (get the closest minute within the day) and the tip percentage on the fare?
* Did the trip time correlate with the cost of the trip?
  * What about the tip amount?
* Which cab tended to generate the most revenue, on average, when picking people up in Manhattan?
* What was the average cost of all of the trips that originated in Brooklyn?
* Which driver made the most money overall? Assume the only money made was from tips.
  * Which driver made the most money on average?
  * Which driver made the most money in each borough?
* What was the average trip distance and trip cost for intra-borough (same starting/ending borough) trips?
  1. For inter-borough (different starting/ending borough) trips?
* Which borough had the cheapest tippers (had the smallest average tip percentage)? Assume that if a trip starts within some borough, then that trip belongs in that borough.
* Which driver logged the most miles in this dataset?
* What was the average toll amount for intra-borough rides? For inter-borough  rides?

In [12]:
import pandas as pd
import numpy as np
import math as math
#%qtconsole

In [7]:
queensCenter = ((40.800760+40.542920)/2,(-73.700272-73.962616)/2)
brookCenter = ((40.739877+40.57042)/2,(-73.864754-74.04344)/2)
bronxCenter = ((40.915255+40.785743)/2,(-73.765274-73.933406)/2)
manhattanCenter = ((40.874663+40.701293)/2,(-73.910759-74.018721)/2)
siCenter = ((40.651812+40.477399)/2,(-74.034547-74.259090)/2)
boroughDict = {}
boroughDict["queens"] = queensCenter
boroughDict["brooklyn"] = brookCenter
boroughDict["bronx"] = bronxCenter
boroughDict["manhattan"] = manhattanCenter
boroughDict["staten"] = siCenter

(40.67184, -73.831444)

In [ ]:
def getBoroughFromLatLong(longitude,latitude):
    
    minBorough = boroughDict.keys()[0]
    minLat
    for borough in boroughDict:

In [2]:
tripData = pd.read_csv("/Users/sergey.fogelson/code/flatiron_school/intro-datascience-workshop/day1/nycTaxiData/trip_data_1_trimmed.csv")

In [3]:
fareData = pd.read_csv("./nycTaxiData/trip_fare_1_trimmed.csv")

In [15]:
latlong = tripData[["pickup_latitude","pickup_longitude"]]

         pickup_latitude  pickup_longitude
0              40.757977        -73.978165
1              40.731781        -74.006683
2              40.737770        -74.004707
3              40.759945        -73.974602
4              40.748528        -73.976250
5              40.764252        -73.966743
6              40.743977        -73.995804
7              40.756775        -73.989937
8              40.743137        -73.980072
9              40.786983        -73.977936
10             40.773167        -73.982452
11             40.749294        -73.995560
12             40.791321        -73.971497
13             40.774307        -73.988510
14             40.723221        -73.994911
15             40.708702        -74.010391
16             40.756287        -73.973732
17             40.767704        -73.968925
18             40.769737        -73.962120
19             40.756714        -73.989708
20             40.648766        -73.783310
21             40.771278        -73.956505
22             40.779320        -73.955780
23             40.764679        -73.978439
24             40.749954        -73.992172
25             40.689701        -73.992111
26             40.787735        -73.978653
27             40.769375        -73.965317
28             40.769142        -73.862709
29             40.748310        -73.977127
...                  ...               ...
4999971        40.727482        -73.988716
4999972        40.765568        -73.976273
4999973        40.747406        -73.993156
4999974        40.778809        -73.948082
4999975        40.749016        -73.979843
4999976        40.710999        -74.016373
4999977        40.756992        -73.971771
4999978        40.744663        -73.979362
4999979        40.759075        -73.991989
4999980        40.769943        -73.954498
4999981        40.781807        -73.958153
4999982        40.788940        -73.977608
4999983        40.754417        -73.946785
4999984        40.738735        -74.008057
4999985        40.753384        -73.989548
4999986        40.763927        -73.972740
4999987        40.782406        -73.971352
4999988        40.763493        -73.969551
4999989        40.726276        -73.980461
4999990        40.751152        -73.990868
4999991        40.773708        -73.945869
4999992        40.776115        -73.961845
4999993        40.735153        -73.979713
4999994        40.774006        -73.957794
4999995        40.752373        -73.975250
4999996        40.769478        -73.984795
4999997        40.761143        -73.990685
4999998        40.755478        -73.976257
4999999        40.733463        -73.993210
5000000        40.739491        -74.001862

[5000001 rows x 2 columns]